### ISSUE TITLE
Benchmark hash functions

### ISSUE THREAD

**Issue by cyann** [ystorian/ulys#4]
Before settling on one hash function, benchmark them.

**Comment by cyann** [comment]
Some hash functions to test:

- xxHash [xxhash-rust](https://github.com/DoumanAsh/xxhash-rust)
  - benchmark both **xxh32** and **xxh3**
  - xxh32 could be a good choice since it can be used on low-power CPUs (e.g. Arduino)
- FNV-1a [fnv-rs](https://github.com/Crypto-Spartan/fnv-rs)
  - fnv_rs::[Fnv32](https://docs.rs/fnv_rs/latest/fnv_rs/struct.Fnv32.html) should work since we need only 32 bits

**Comment by adriantombu** [comment]
After some benchmarks we'll settle with `xxh3` from https://crates.io/crates/xxhash-rust for now
